name: Automerge

on:
  pull_request:
    types: [ labeled, unlabeled, synchronize, opened, edited, ready_for_review, reopened, review_requested, review_request_removed ]
  check_suite: 
    types: [completed]
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "automerge,!wip"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "pull-request-title"
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "10000"
