name: Automerge

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: automerge
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "automerge,!wip"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "pull-request-title"
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "10000"
